# Generated by Django 5.2.4 on 2025-09-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201119_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscrm',
            old_name='Status_name',
            new_name='status_name',
        ),
    ]
